#!/usr/bin/env node

	//Add necesary libraries.
var fs = require("fs"),
	crypto = require('crypto'),
	randomness = require('./lib/salt');
	
	//Read the file.
var inputFile = process.argv[2],
	file = fs.createReadStream(inputFile);

	//Generate salt and key.
var	iv = new Buffer(randomness.iv, 'base64'),
	salt = randomness.salt,
	key = new Buffer(randomness.key, 'base64');

//Write output file.
var	outputFile = process.argv[4],
	output = fs.createWriteStream(outputFile);

//Create cypher.
var	encrypt = crypto.createCipheriv('aes-256-gcm', key, iv);

//Encrypt.
file.pipe(encrypt).pipe(output);

//Add authtag, salt and iv to file.
output.on('finish', function () {
	var tag = encrypt.getAuthTag();
	fs.appendFile(outputFile, tag.toString('base64'), {encoding: 'base64'});
	fs.appendFile(outputFile, salt, {encoding: 'base64'});
	fs.appendFile(outputFile, iv.toString('base64'), {encoding: 'base64'});
});