#!/usr/bin/env node

var crypto = require('crypto');

var password = process.argv[3];

function generateBytes (number) {
	return crypto.randomBytes(number).toString('base64');
}

var iv = generateBytes(12);
var salt = generateBytes(128);

var pdkdf = crypto.pbkdf2Sync(password, salt, 80000, 32, 'SHA512', function(err, key) {
	if (err) throw err;
});

module.exports.iv = iv.toString('base64');
module.exports.salt = salt.toString('base64');
module.exports.key = pdkdf.toString('base64');